// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuWyKEX--gzeaEU58ulXQmqhPUqDm9LF8',
    appId: '1:74802460876:web:be36180f2ca219ba40aa69',
    messagingSenderId: '74802460876',
    projectId: 'tik-tok-sean510',
    authDomain: 'tik-tok-sean510.firebaseapp.com',
    storageBucket: 'tik-tok-sean510.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsysByO0HugHF1v_OrYsSsLBF3i1cJ6bU',
    appId: '1:74802460876:android:a30b5d49dc0c053f40aa69',
    messagingSenderId: '74802460876',
    projectId: 'tik-tok-sean510',
    storageBucket: 'tik-tok-sean510.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFZnr4yhKJ9BZu5MCBfJkPRW8CBCVscVc',
    appId: '1:74802460876:ios:d8dd94d453fc228840aa69',
    messagingSenderId: '74802460876',
    projectId: 'tik-tok-sean510',
    storageBucket: 'tik-tok-sean510.appspot.com',
    iosClientId: '74802460876-fmtnb6o8dtj61qgjn77eep1h176su3m6.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokCloneAndroid',
  );
}
